let information_list=[
    [
        'Solo_Leveling',
        '150',
        '9.31',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
        "16160",
        "/",
        ".jpg"
    ],
    [
        'Fullmetal_alchemist',
        '108',
        '9.33',
        'Japan',
        'English',
        'https://youtu.be/dqDB6gQLbPM',
        'Ended',
        "2169",
        "/p_0000",
        ".png"
    ],
    [
        'Hunter_X_Hunter',
        '389',
        '8.95',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
        "3041",
        "/",
        ".jpg" 
    ],
    [
        'Vinland_Sage',
        '182',
        '9.1',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
        "7933",
        "/",
        ".jpg" 
    ],
    [
        'The_promise_neverland',
        '181',
        '9.1',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
        "15961",
        "/",
        ".jpg" 
    ],
    [
        'Vinland_Sage',
        '182',
        '9.1',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
        "7933",
        "/",
        ".jpg" 
    ]

]


var names_list=[
"Solo-Leveling",    
"Fullmetal-alchemist",
"Hunter-x-hunter",
"Vinland-sage",
"The-promise-neverland",
"Steins-gate",
"Code-geass",
"Haikyuu!!",
"Fire-forces",
"Boku-no-hero",
"Dororo",
"Death-note",
"Boruto",
"Naruto",
"Dragon-ball-super",
"One-punch-man",
"Beastars",
"Over-lord",
"Bleach",
"Dumbel-nano-kilo",
"gokushufudou",
"Mob-psycho-100",
"Edens-zero"
];

