let information_list=[
    [
        'solo-leveling-3',
        '150',
        '9.31',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
    ],
    [
        'The-Beginning-After-The-End',
        '104',
        '9.26',
        'Japan',
        'English',
        'https://youtu.be/02E6ZQLwsPI',
        'TurtleMe'
    ],
    [
        'Jujutsu-Kaisen',
        '147',
        '9.24',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous'
    ],
    [
        'Shingeki-no-Kyojin',
        '145',
        '9.6',
        'Japan',
        'English',
        'https://youtu.be/ZefrVAetxVI',
        'tttt'
    ],
    [
        'Boku-no-Hero-Academia',
        '311',
        '9.16',
        'Japan',
        'English',
        'https://youtu.be/Q8bmv-14OVI',
        'HORIKOSHI Kouhei'
    ],
    [
        'Berserk',
        "363",
        "9.11",
        "Japan",
        "Enlish",
        "#",
        "MIURA Kentaro"
    ],
    [
        'black-clover',
        '292',
        '9.18',
        'Japan',
        'English',
        '#',
        'Tabata Yuuki'
    ],
    [
        'one-piece1',
        '1000',
        '9.18',
        'Japan',
        'English',
        '#',
        'oda'
    ],
    [
        'tokyo_ghoul_re',
        '179',
        '9.14',
        'Japan',
        'English',
        'https://youtu.be/ETHpMMV8rJU',
        "ISHIDA Sui"
    ],
    [
        'Tales-of-Demons-and-Gods',
        '326',
        '8.6',
        'Japan',
        'English',
        '#',
        'Mad Snail'
    ]

]
var names_list=[
"Solo-Leveling",
"The-Beginning-After-The-End",
"Jujutsu-Kaisen",
'Shingeki-no-Kyojin',
"Boku-no-Hero-Academia",
"Berserk",
'black-clover',
'One-piece',
'Tokyo-Ghoul',
'Tales-of-Demons-and-Gods'
];