let information_list=[
    [
        'solo-leveling-3',
        '150',
        '9.31',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'continuous',
        '10 years ago, after “the Gate” that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as "Hunters". However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. Im someone who has to risk his life in the lowliest of dungeons, the "World s Weakest". Having no skills whatsoever to display, I barely earned the required money by fighting in low-leveled dungeons… at least until I found a hidden dungeon with the hardest difficulty within the D-rank dungeons! In the end, as I was accepting death, I suddenly received a strange power, a quest log that only I could see, a secret to leveling up that only I know about! If I trained in accordance with my quests and hunted monsters, my level would rise. Changing from the weakest Hunter to the strongest S-rank Hunter!'
    ],
    [
        'The-Beginning-After-The-End',
        '104',
        '9.26',
        'Japan',
        'English',
        'https://youtu.be/02E6ZQLwsPI',
        'TurtleMe',
        'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Beneath the glamorous exterior of a powerful king lurks the shell of man, devoid of purpose and will.'
    ],
    [
        'Jujutsu-Kaisen',
        '147',
        '9.24',
        'Japan',
        'English',
        'https://youtu.be/EWLYcDLXHQE',
        'Akutami Gege',
        'Yuuji is a genius at track and field. But he has zero interest running around in circles, he s happy as a clam in the Occult Research Club. Although he s only in the club for kicks, things get serious when a real spirit shows up at school! Life s about to get really strange in Sugisawa Town #3 High School!'
    ],
    [
        'Shingeki-no-Kyojin',
        '145',
        '9.6',
        'Japan',
        'English',
        'https://youtu.be/ZefrVAetxVI',
        'ISAYAMA Hajime',
        'Several hundred years ago, humans were nearly exterminated by giants. Giants are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of giants.Flash forward to the present and the city has not seen a giant in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a super giant that appears out of thin air. As the smaller giants flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single giant and take revenge for all of mankind.Nominated for the 4th Manga Taisho Awards (2011) and winner of the 35th annual Kodansha Manga award for Best Shounen.'
    ],
    [
        'Boku-no-Hero-Academia',
        '311',
        '9.16',
        'Japan',
        'English',
        'https://youtu.be/Q8bmv-14OVI',
        'HORIKOSHI Kouhei',
        'The story is set in the modern day, except people with special powers have become commonplace throughout the world. A boy named Izuku Midoriya has no powers, but he still dreams.'
    ],
    [
        'Berserk',
        "363",
        "9.11",
        "Japan",
        "Enlish",
        "#",
        "MIURA Kentaro",
        "Gattsu, known as the Black Swordsman, seeks sanctuary from the demonic forces that persue himself and his woman, and also vengeance against the man who branded him as an unholy sacrifice. Aided only by his titanic strength, skill and sword, Gattsu must struggle against his bleak destiny, all the while fighting with a rage that might strip him of his humanity. Berserk is a dark and brooding story of outrageous swordplay and ominous fate, in the theme of Shakespeare's MacBeth."
    ],
    [
        'black-clover',
        '292',
        '9.18',
        'Japan',
        'English',
        '#',
        'Tabata Yuuki',
        "Aster and Yuno were abandoned together at the same church, and have been inseparable since. As children, they promised that they would compete against each other to see who would become the next sorcerous emperor. However, as they grew up, some differences between them became plain. Yuno was a genius with magic, with amazing power and control, while Aster could not use magic at all, and tried to make up for his lack by training physically. When they received their grimoires at age 15, Yuno got a spectacular book with a four-leaf-clover (most people receive a three-leaf-clover), while Aster received nothing at all. However, when Yuno was threatened, the truth about Aster's power was revealed-- he received a five-leaf-clover grimoire, a 'black clover' book of anti-magic. Now the two friends are heading out in the world, both seeking the same goal! [tethysudst]"
    ],
    [
        'one-piece1',
        '1000',
        '9.18',
        'Japan',
        'English',
        '#',
        'oda',
        'Greatness, Glory, Gold. A Pirate Named Gold Roger also known as the Pirate King has conquered this all. He was executed with an unknown reason but before he died he had revealed his last word about The legendary Treasure named One Piece which was hidden in the Grand Line. 22 years after his Death, A Pirate named Monkey D. Luffy appeared and has only one Goal, To Become the Next "Pirate King" and Find The Treasure "One Piece". This Start The Never Ending Adventure. Monkey D. Luffy, inspired by his childhood hero "Red-Haired" Shanks, sets out on a journey to find the legendary treasure One Piece, to become the new Pirate King, and after eating the devil s fruit gains the power to do so. To accomplish this, he must reach the end of the most deadly and dangerous ocean: The Grand Line. But first he must find a crew.'
    ],
    [
        'tokyo_ghoul_re',
        '179',
        '9.14',
        'Japan',
        'English',
        'https://youtu.be/ETHpMMV8rJU',
        "ISHIDA Sui",
        "The brand new sequel of Toukyou Kushu resumes after a time skip and new characters make their appearance."
    ],
    [
        'Tales-of-Demons-and-Gods',
        '326',
        '8.6',
        'Japan',
        'English',
        '#',
        'Mad Snail',
        'Trying to protect the city which in the coming future was being assaulted by beast and ended up being destroyed as well as protecting his lover, friends and family who died by the beast assault. And to destroy the Sacred family whom abandon their duty and betrayed city in his past life.'
    ],
    [
        'Nanatsu-no-Taizai',
        '346',
        '8.96',
        'Japan',
        'English',
        'https://youtu.be/wxcvbL6o55M',
        'Suzuki Nakaba',
        'The "Seven Deadly Sins", a group of evil knights who conspired to overthrow the kingdom of Britannia, were said to have been eradicated by the Holy Knights, although some claim that they still live. Ten years later, the Holy Knights have staged a Coup d état and assassinated the king, becoming the new, tyrannical rulers of the kingdom. Elizabeth, the king s only daughter, sets out on a journey to find the "Seven Deadly Sins", and to enlist their help in taking back the kingdom.'
    ],
    [
        'Haikyuu',
        '402',
        '9.13',
        'Japan',
        'English',
        'https://youtu.be/JOGp2c7-cKc',
        'FURUDATE Haruichi',
        "Hinata Shouyou, upon seeing a volleyball match, is aiming to become 'The Small Giant', and joins his middle school volleyball club. After finding new members, they set out for the middle school tournament, where they've cross paths with a formidable school with the 'King of the Upper Court', Kageyama Tobio. Although their team lost, Shouyou is still determined to aim for the top and exact revenge on Kageyama. Upon entering high school, he recieved the biggest surprise--he and Kageyama are on the same school and club!"
    ],
    [
        'Jojos-Bizarre-Adventure',
        '645',
        '10',
        'Japan',
        'English',
        'https://youtu.be/XUhVCoTsBaM',
        'Araki Hirohiko',
        'Is a young man with exceptional abilities and talent, some times a true gentleman, some times a charlatan, and some times a high school kid, but always has mega awesome powers like breathing really good or stopping time, or he can smash a camera to take pictures far away. His father figures usually dies or isn t around I guess???'
    ],
    [
        'kimetsu-no-yaiba',
        '205',
        '9.16',
        'Japan',
        'English',
        'https://youtu.be/So_71Qwo06U',
        'Gotouge Koyoharu',
        'Tanjiro is the eldest son in a family that has lost its father. Tanjiro visits another town one day to sell charcoal, but ends up staying the night at someone else s house instead of going home because of a rumor about a demon that stalks a nearby mountain at night. When he goes home the next day, tragedy is waiting for him.'
    ],
    [
        'yakusoku-no-neverland',
        '181',
        '9.15',
        'Japan',
        'English',
        'https://youtu.be/ApLudqucq-s',
        'Kaiu Shirai',
        'Emma and her friends have a pretty good life at the orphanage they grew up in. Though the rules may be strict, the caretaker is kind. But why are the children forbidden from ever leaving...? '
    ],
    [
        'Spirit-Blade-Mountain',
        '458',
        '8.91',
        'Japan',
        'English',
        '#',
        'Xian man dong man',
        'There’s a mountain called Spirit Blade Mountain. Inside or by the mountain resides Wizards, also known as Spirit Blade Masters. Together they form the Spirit Blade clan. Spirit Blade is synonymous with magic, as it’s the Blade your Spirit forms. The current relation between the Mountain and the actual Spirit Blade is unknown. How the Spirit Blade manifests itself and how it is used is also unknown. However, not everyone can learn magic. Only those with the “Spirit Base” can learn the basics of magic, and even then, you have to practice it to become good. It seems Spirit Blade Masters command a great deal of awe and respect in the kingdom'
    ],
    [
        'The-Ravages-of-Time',
        '552',
        '8.99',
        'Japan',
        'English',
        '#',
        'Chen Mou',
        'Nearly 2000 years ago, the prosperous Han dynasty of China collapsed. Heroes rose and fell, and three nations emerged--Wei, Shu, and Wu. Historians refer to this period as the Three Kingdoms period. The romance of the three kingdoms is an intriguing tale of heroic deeds, of alliance forged and broken, of loyalty and betrayal...Hong Kong artist Chan Mou retells this classic tale in "The Ravages of Time" from the perspective of the Sima clan, which in the end united the three kingdoms. Readers will be attracted by an array of well-developed characters and Chan Mous own unique top-notch art-style. Whether you have played Dynasty Warriors or not, this is definitely worth a read!'
    ],
    [
        'bleach1',
        '686',
        '9.16',
        'Japan',
        'English',
        '#',
        'Kubo Tite',
        'Ichigo Kurosaki has always been able to see ghosts, but this ability doesnt change his life nearly as much as his close encounter with Rukia Kuchiki, a soul reaper and member of the mysterious Soul Society. While fighting a hollow, an evil spirit that preys on humans who display spiritual energy, Rukia attempts to lend Ichigo some of her powers so that he can save his family; but much to her surprise, Ichigo absorbs every last drop of her energy. Now a full-fledged soul reaper himself, Ichigo quickly learns that the world he inhabits is one full of dangerous spirits and, along with Rukia, its Ichigos job to protect the innocent from hollows and help the spirits themselves find peace. In 2005, Bleach was awarded the Shogakukan Manga Award in the shounen category.'
    ],
    [
        'Tower-of-God-1',
        '485',
        '9.54',
        'Japan',
        'English',
        '#',
        'Slave In Utero',
        'What do you desire? Fortune? Glory? Power? Revenge? Or something that surpasses all others? What ever you desire, that is here. Tower of God.'
    ],
    [
        'Clover-TETSUHIRO-Hirakawa',
        '402',
        '8.45',
        'Japan',
        'English',
        '#',
        'TETSUHIRO Hirakawa',
        'Three childhood friends are meeting again in high school. Hayato (see cover) the crazy one, Kenji the big one who wouldnt hurt a fly, and Tomoki the solitary one are the main characters of this fighting manga.'
    ],
    [
        'Noblesse',
        '545',
        '8.19',
        'Japan',
        'English',
        '#',
        'Lee Gwang Su',
        'For 820 years he had slumbered with no knowledge of mankinds advancement and scientific progress. The land which he once knew has become an unfamiliar place with new technology, attitudes, and lifestyles. Upon awakening, Cadis Etrama Di Raizel (aka Rai), seeks to familiarize himself with this era. He locates a loyal servant of his, Frankenstein, who is currently the principal of a South Korean High School. Rai decides that this school is the perfect place to help him learn about the modern world, enrolls, and begins associating a group of good-natured students in order to blend in. But this new world is no safer than the old; and the dignified, bewildered, technologically inept Rai finds himself embroiled in adventures both ridiculous and dangerous.'
    ],
    [
        'The-God-of-High-School-1',
        '467',
        '9.12',
        'Japan',
        'English',
        '#',
        'PARK Yong Je',
        'While an island half-disappearing from the face of the earth, a mysterious organization is sending out invitations for a tournament to every skilled fighter in the world. “If you win you can have ANYTHING you want”They’re recruiting only the best to fight the best and claim the title of The God of high school! '
    ],
    [
        'naruto1',
        '700',
        '9.56',
        'Japan',
        'English',
        '#',
        'Kishimoto Masashi',
        "Twelve years before the events at the focus of the series, the nine-tailed demon fox attacked Konohagakure. It was a powerful demon fox; a single swing of one of its nine tails would raise tsunamis and flatten mountains. It raised chaos and slaughtered many people, until the leader of the Leaf Village - the Fourth Hokage - defeated it by sacrificing his own life to seal the demon inside a newly-born child. That child's name was Naruto Uzumaki."
    ],
    [
        'one-punch-man',
        '145',
        '8.12',
        'Japan',
        'English',
        '#',
        'Yusuke Murata',
        '“I’m just an average guy who serves as an average hero.  In a world of superheroes and villains, Saitama appears to be a plain man -- from his lifeless expression to his sluggish personality, nothing stands out. But once danger strikes, he’s an insanely powerful superhero that can take down villains with a single punch! Although his strength keeps the city safe, Saitama can’t help but grow bored with how easily his opponents are defeated.'
    ],
    [
        'dr-stone',
        '191',
        '0',
        'Japan',
        'English',
        '#',
        'Inagaki Riichiro',
        'The science-fiction adventure series follows what happens when suddenly the world s biggest-ever "crisis" arrives.'
    ],
    [
        'apotheosis-elevation-to-the-status-of-a-god',
        '753',
        '7.5',
        'China',
        'English',
        '#',
        '-',
        'Luo Zheng, now a humble slave was born as the eldest son of a wealthy family. Due to his familys decline, the kidnapping of his sister by a powerful force, he can now only be stepped upon by others. However, heaven never seals off all exits. An ancient book left by his father reveals a secret divine technique, giving the reader immense power! But what is behind this power? This is a contest against fate'
    ],
    [
        'The-Gamer',
        '373',
        '8.95',
        'Korea',
        'English',
        '#',
        'Sung San Young',
        'What would happen if your world suddenly turned into a game?If you could level up and raise your stats?An adventure of a life-turned-game'
    ],
    [
        'Fairy-Tail',
        '545',
        '8.94',
        'Japan',
        'English',
        'https://youtu.be/4KSN7mxhiYE',
        'Mashima Hiro',
        'Celestial wizard Lucy wants to join the Fairy Tail, a guild for the most powerful wizards. But instead, her ambitions land her in the clutches of a gang of unsavory pirates led by a devious magician. Her only hope is Natsu, a strange boy she happens to meet on her travels. Natsu s not your typical hero - but he just might be Lucy s best hope.'
    ],
    [
        'the-last-human',
        '343',
        '8.23',
        'China',
        'English',
        '#',
        'Amazing Works',
        'Zuo Tianchen is the last living human in a mutated zombie-infested city. Just when he was sure hed died, he finds his soul returned to just before that ill-fated day ten years ago. He swears hell protect the people important to him this time round and reunite with his past lover. Watch his struggles to survive equipped with his memory of the next ten years!'
    ],
    [
        'Kingdom',
        '678',
        '9.21',
        'Japan',
        'English',
        '#',
        'Hara Yasuhisa',
        'Millions of years have passed since the times of legends, when the worlds of man and gods were still the same. In these times it was the desires of man that moved the world. It is the era of the 500 year war: The warring states period. Kingdom is the story of a young boy named Shin who grew into a great general and all the trials and bloodshed that lead him there.'
    ],
    [
        'Death-Note',
        '112',
        '9.15',
        'Japan',
        'English',
        '#',
        'OBATA Takeshi',
        'An overachieving 12th grader, Yagami Light is an aspiring young man who seems destined for success. Unfortunately, his daily habits bore his incredible intelligence--So when a strange black notebook falls from the heavens during his class, it isn t long before he takes it for himself. In his room, he finds, to his horror/fascination, that the Death Note is real, and owned by Ryuk, a Shinigami (Death God).'
    ]
]
var names_list=[
"Solo-Leveling",
"The-Beginning-After-The-End",
"Jujutsu-Kaisen",
'Shingeki-no-Kyojin',
"Boku-no-Hero-Academia",
"Berserk",
'black-clover',
'One-piece',
'Tokyo-Ghoul',
'Tales-of-Demons-and-Gods',
'Nanatsu-no-Taizai',
'Haikyuu',
'Jojos-Bizarre-Adventure',
'kimetsu-no-yaiba',
'yakusoku-no-neverland',
'Spirit-Blade-Mountain',
'The-Ravages-of-Time',
'Bleach',
'Tower-of-God',
'Clover-TETSUHIRO-Hirakawa',
'Noblesse',
'The-God-of-High-School',
'Naruto',
'one-punch-man',
'Dr-stone',
'apotheosis-elevation-to-the-status-of-a-god',
'The-Gamer',
'Fairy-Tail',
'THE-LAST-HUMAN',
'KINGDOM',
'DEATH-NOTE'
];